### ISSUE TITLE
Could not find 'libvlc.dll'

### ISSUE THREAD

**Issue by AllenWu233** [hemantapkh/PyBirthdayWish#47]
```
Traceback (most recent call last):
  File "E:\Python_work\program\PyBirthdayWish\PyBirthdayWish.py", line 7, in <module>
    import vlc
  File "E:\Python_work\program\PyBirthdayWish\birthday_venv\lib\site-packages\vlc.py", line 220, in <module>
    dll, plugin_path  = find_lib()
  File "E:\Python_work\program\PyBirthdayWish\birthday_venv\lib\site-packages\vlc.py", line 180, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "E:\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'E:\Python_work\program\PyBirthdayWish\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
help me pls😭

**Comment by 0xlxy** [comment]
https://stackoverflow.com/questions/70554558/vlc-library-error-cannot-import-it-into-code
It works on my end after installing the latest [apple-silicon vlc](https://get.videolan.org/vlc/3.0.18/macosx/vlc-3.0.18-arm64.dmg).

**Comment by TheGreatSimo** [comment]
pip install python-vlc
